@extends('website.layout')
@section('title') من نحن |Pets Zone @endsection
@section('content')

<style>
   div, span. p, li, strong, h1,h2,h3,h4,h5,h6{
        font-family: 'Cairo' !important;
        line-height: normal !important;
    }
    .highlight{
        font-weight: 600;
        font-size: 19px;
    }
</style>
    <!-- Breadcrumb Start -->
    <div class="breadcrumb-area pt-60 pb-55 pt-sm-30 pb-sm-20">
        <div class="container">
            <div class="breadcrumb">
                <ul>
                    <li><a href="/">الرئيسية</a></li>
                    <li class="active"><a href="#">ارشادات</a></li>
                </ul>
            </div>
        </div>
        <!-- Container End -->
    </div>
    <!-- Breadcrumb End -->

    <div class="about-main-area">
        <div class="container">
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:center;line-height:107%;'><strong><span style='font-size:16px;line-height:107%;' class="highlight">كيف نعتني بالقطة بالطريقة الصحيحة</span></strong></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:center;line-height:18.0pt;background:white;'><span dir="LTR" style='font-size:12px;color:black;'>&nbsp;</span></p>
            <ul style="list-style-type: undefined;margin-left:-6.25px;">
                <li><strong><span style=''>طعام القطة:</span></strong><strong><span style='font-size:9.0pt;color:black;'>&nbsp;</span></strong>
                    <ol style="list-style-type: circle;">
                        <li><span style=''>يجب الإهمام بنوعية الطعام المقدم للقطة حيث يختلف طعام كل حيوان أليف عن أي حيوان آخر ، لذلك يجب مراعاة هذه النقطة وأخذها بعين الإعتبار ، يجب الإهتمام بالتنويع في طعام القطط ، ويمكن اطعام القطط من طعام القطط الخاص المنتشر في المولات التجارية والمحلات الخاصة بالحيوانات الأليفة ، كما يمكن إطعام القطة المنزلية من البسكويت الخاص بالقطط ، كذلك يمكن اطعامها من المعلبات والتونة وكذلك يمكن إطعامها بقايا طعام منزلي يناسبها مثل السمك</span></li>
                    </ol>
                </li>
            </ul>
            <p dir="RTL" style='margin-right:0in;margin-left:3.75pt;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:right;line-height:18.0pt;text-indent:3.4pt;background:white;'><span dir="LTR" style='font-size:12px;color:black;'>&nbsp;</span></p>
            <div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:right;line-height:107%;font-size:15px;font-family:"Cairo",sans-serif;'>
                <ul style="margin-bottom:0in;list-style-type: undefined;margin-left:-6.25px;">
                    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:right;line-height:107%;font-size:15px;font-family:"Cairo",sans-serif;'><strong><span style=''>الاهتمام بنظافة القطة:&nbsp;</span></strong></li>
                </ul>
            </div>
            <p dir="RTL" style='margin-right:.5in;margin-left:3.75pt;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:right;line-height:18.0pt;background:white;'><span style='font-size:12px;color:black;'>من المهم جداً الاهتمام بنظافة القط المنزلي ، وخصوصا أن القط هو حيوان أليف يحب النظافة بطبيعته وبفطرته ، فهي تقوم بلعق جسمها للتخلص من الأوساخ والشعر الزائد ، لذلك عليك أن تقوم بتحميم القطط مرة في الأسبوع على الأقل وعليك مراعاة استخدام الشامبو الخاص بالقطط أثناء تحميمها وبعد ذلك قم بتجفيفها</span></p>
            <p dir="RTL" style='margin-right:.5in;margin-left:3.75pt;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:right;line-height:18.0pt;background:white;'><span dir="LTR" style='font-size:12px;color:black;'>&nbsp;</span></p>
            <div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:right;line-height:107%;font-size:15px;font-family:"Cairo",sans-serif;'>
                <ul style="margin-bottom:0in;list-style-type: undefined;">
                    <li style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:right;line-height:107%;font-size:15px;font-family:"Cairo",sans-serif;'><span style=''>يجب مراعاة توفير مكان خاص بالقطة لتنام فيه كما يمكن أن نزينها بسلاسل جميلة وغير مؤذية وهي اكسسوارات منتشرة لدى المحلات الخاصة بمستلزمات العناية بالحيوانات الأليفة</span><span dir="LTR" style='font-size:9.0pt;color:black;'>&nbsp;.</span></li>
                </ul>
            </div>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:12px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:12px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:12px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:center;line-height:107%;'><strong><span style='font-size:16px;line-height:107%;' class="highlight">ماهي الطريقة الصحيحه لحمل القطه ؟</span></strong></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:center;line-height:107%;'><span dir="LTR" style='font-size:12px;line-height:107%;'>&nbsp;<img style="width: 50%;height: 50%;" src="{{asset('website/img/11111.jpg')}}" alt="image" width="1200" height="900"></span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:12px;line-height:107%;'>&nbsp;</span></p>
            <p dir="LTR" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;background:white;'><span dir="RTL" style="font-size:13px;color:#1F1F1F;">يُخبرنا الطبيب البيطري أن &ldquo;مفتاح حمل القط بأمان هو جعله يشعر بالدعم&rdquo;، فإذا شعر بالدعم والأمان لن يبدأ بالركل في الهواء بأرجله الخلفية، مما يقلل أيضاً من فرص تعرضك للخدوش. وللقيام بذلك، ضع يد واحدة على صدر القط، بينما تكون اليد الأخرى على منطقة البطن، لتوفير الدعم اللازم، ثم ابدأ برفع القط بهذه الطريقة، وستجده مثبت جيداً بين يديك وغير متدلي. وإذا أردت منعه من التسلل والهرب، فالسر يكمن في الضغط عليه قليلاً وبلطف. فإذا كنت بالفعل قد التقطته بين ذراعيك، فمن المستحسن أن تجعله قريباً من جسمك</span><span style="font-size:13px;color:#1F1F1F;">.</span></p>
            <p dir="LTR" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;background:white;'><span dir="RTL" style="font-size:13px;color:#1F1F1F;">وإذا أردته أن يظل ثابتاً لتتمكن من قص أظافره على سبيل المثال، فقربه أكثر من جسمك، ولا تخف من فعل هذا الأمر، لأن هذه الوضعية ستُقلل شعوره بالألم بالإضافة إلى أنها ستشعره بالحماية والأمان، وبالتالي سيتوقف عن الحركة</span><span style="font-size:13px;color:#1F1F1F;">.</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:13px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:12px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:center;line-height:107%;'><strong><span style='font-size:16px;line-height:107%;' class="highlight">أخطاء حاول أن لا تقع فيها عند تدريب حيوانك الأليف :</span></strong></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:12px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;text-align:right;background:white;vertical-align:baseline;'><span style="font-size:13px;color:#181818;border:none windowtext 1.0pt;padding:0in;">- أعطاؤه مكافئات دون سبب وذلك سيجعله يفقد القيم والاداب التي قد إكتسبها.&nbsp;</span></p>
            <p dir="LTR" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;background:white;vertical-align:baseline;'><br></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;text-align:right;background:white;vertical-align:baseline;'><span style="font-size:13px;color:#181818;border:none windowtext 1.0pt;padding:0in;">- عزله عن المجتمع وحجبه عن بقية الحيوانات حيث يجب أن يكون هناك تفاعل بين الحيوانات وبين الأشخاص المحيطين بها</span></p>
            <p dir="LTR" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;background:white;vertical-align:baseline;'><br></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;text-align:right;background:white;vertical-align:baseline;'><span style="font-size:13px;color:#181818;border:none windowtext 1.0pt;padding:0in;">- ترك الحيوان بمفرده لمدة طويلة, ذلك سيجعل سلوكه منطوي وغير سوي</span></p>
            <p dir="LTR" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;background:white;vertical-align:baseline;'><br></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;text-align:right;background:white;vertical-align:baseline;'><span style="font-size:13px;color:#181818;border:none windowtext 1.0pt;padding:0in;">- اهمال المحافظة على النشاط الذهني للحيوان, ذلك سيؤدي إلى إحساسه بالملل والاحباط&nbsp;</span></p>
            <p dir="LTR" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;background:white;vertical-align:baseline;'><br></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;text-align:right;background:white;vertical-align:baseline;'><span style="font-size:13px;color:#181818;border:none windowtext 1.0pt;padding:0in;">- عدم توفير جو مناسب للحيوان في المنزل, يجب توفير مكان خاص به لينام فيه ومكان خاص لطعامه</span></p>
            <p dir="LTR" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;background:white;vertical-align:baseline;'><br></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:16px;margin:0in;margin-bottom:.0001pt;text-align:right;background:white;vertical-align:baseline;'><span style="font-size:13px;color:#181818;border:none windowtext 1.0pt;padding:0in;">- يجب على مربي الحيوان الأليف عدم رفع الصوت عليه ( الصراخ ) وعدم تعنيفه, لأن ذلك سيؤثر نفسيا على الحيوان الأليف&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:13px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:13px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:13px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:right;line-height:107%;'><span style='font-size:13px;line-height:107%;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:center;line-height:107%;'><strong><span style='font-size:16px;line-height:107%;' class="highlight">ما هي الأطعمة التي لايجب إعطائها الكلاب؟&nbsp;</span></strong></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:8.0pt;text-align:center;line-height:107%;'><strong><span style='font-size:16px;line-height:107%;' class="highlight">وماهي الأطعمه التي تحبها الكلاب ؟</span></strong></p>
            <p dir="LTR" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:11.25pt;text-align:center;line-height:normal;background:white;'><strong><span dir="RTL" style='font-size:13px;color:#2C2F34;'>&nbsp;</span></strong></p>
            <p dir="LTR" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:18.75pt;text-align:right;line-height:26.25pt;background:white;'><span dir="RTL" style="font-size:13px;color:#2C2F34;">هناك الكثير من المربيين يقدمون للكلاب أطعمة لا يجب تناولها أبداً، لكن بالتأكيد يأتي ذلك بنتائج سلبية على صحة الكلاب، لذا إليك قائمة بأخطر الأطعمة التى لا يُنصح بتقديمها للكلاب</span><span style="font-size:13px;color:#2C2F34;">:</span></p>
            <ul style="margin-bottom:0in;margin-top:0in;" type="disc">
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:     15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><strong><span style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">إكسيليتول</span></strong><strong><span dir="LTR" style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">:</span></strong><span dir="LTR" style='font-size:13px;'>&nbsp;</span><span style='font-size:13px;'>يتم تحلية الحلوى والعلكة ومعجون الأسنان والسلع المخبوزة وبعض أطعمة الحمية بإستخدام إكسيليتول وهو نوع من التحلية يمكن أن يتسبب في انخفاض نسبة&nbsp;</span><span style="color:windowtext;"><a href="https://www.almrsal.com/post/926284" title="معدل السكر الطبيعي في سن الأربعين"><span style='font-size:13px;color:#2080C7;border:none windowtext 1.0pt;padding:0in;'>السكر</span></a></span><span dir="LTR" style='font-size:13px;'>&nbsp;</span><span style='font-size:13px;'>في دم الكلب ويمكن أن يتسبب أيضًا في فشل الكبد، وتشمل الأعراض المبكرة بـ القيء والخمول</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:     15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><strong><span style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">الأفوكادو</span></strong></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:     15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><strong><span style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">البصل والثوم</span></strong><strong><span dir="LTR" style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">:</span></strong><span dir="LTR" style='font-size:13px;'>&nbsp;</span><span style='font-size:13px;'>يمكن للبصل والثوم قتل خلايا الدم الحمراء لدى الكلاب مما يسبب فقر الدم</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:     15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><strong><span style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">القهوة والشاي وأنواع&nbsp;</span></strong><span style="color:windowtext;"><a href="https://www.almrsal.com/post/880076" title="نسبة الكافيين"><strong><span style='font-size:13px;color:#2080C7;border:none windowtext 1.0pt;padding:0in;'>الكافيين</span></strong></a></span><strong><span dir="LTR" style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">&nbsp;</span></strong><strong><span style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">الأخرى</span></strong><strong><span dir="LTR" style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">:</span></strong><span dir="LTR" style='font-size:13px;'>&nbsp;</span><span style='font-size:13px;'>يمكن أن يكون الكافيين قاتلاً للكلاب لذلك احترس بإبقاء الكلاب بعيدة عن القهوة والشاي والكاكاو والشوكولاتة ومشروبات الطاقة</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:     15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><strong><span style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">العنب والزبيب</span></strong><strong><span dir="LTR" style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">:</span></strong><span dir="LTR" style='font-size:13px;'>&nbsp;</span><span style='font-size:13px;'>يمكن أن يسبب&nbsp;</span><span style="color:windowtext;"><a href="https://www.almrsal.com/post/755850" title="فوائد العنب"><span style='font-size:13px;color:#2080C7;border:none windowtext 1.0pt;padding:0in;'>العنب</span></a></span><span dir="LTR" style='font-size:13px;'>&nbsp;</span><span style='font-size:13px;'>والزبيب الفشل الكلوي في الكلاب، فمجرد كمية صغيرة يُصاب الكلب بالمرض والقيء بشكل متكرر والخمول والاكتئاب</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:     15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><strong><span style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">الشوكولاتة</span></strong><strong><span dir="LTR" style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">:</span></strong><span dir="LTR" style='font-size:13px;'>&nbsp;</span><span style='font-size:13px;'>يعرف معظم الناس أن&nbsp;</span><span style="color:windowtext;"><a href="https://www.almrsal.com/post/1064216" title="الشوكولاتة"><span style='font-size:13px;font-family:     "Times New Roman",serif;color:#2080C7;border:none windowtext 1.0pt;padding:0in;'>الشوكولاتة</span></a></span><span dir="LTR" style='font-size:13px;'>&nbsp;</span><span style='font-size:13px;'>ضارة للكلاب، فإن المشكلة في الشوكولاتة هي الثيوبرومين وهو عنصر موجود في جميع أنواع الشوكولاتة حتى الشوكولاتة &nbsp;، فيمكن للشوكولاتة أن تتسبب في تقيؤ الكلب وإصابته بالإسهال وأيضًا مشاكل في&nbsp;</span><span style="color:     windowtext;"><a href="https://www.almrsal.com/post/943712" title="جدول دقات القلب حسب العمر"><span style='font-size:13px;color:#2080C7;border:none windowtext 1.0pt;padding:0in;'>القلب</span></a></span><span dir="LTR" style='font-size:13px;'>&nbsp;</span><span style='font-size:13px;'>والرعشة والنوبات والموت</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:     15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><strong><span style="font-size:13px;border:none windowtext 1.0pt;padding:0in;">الأطعمة والمشروبات السكرية</span></strong></li>
            </ul>
            <p dir="RTL" style='margin-right:.5in;margin-left:15.0pt;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:justify;line-height:24.0pt;background:white;'><span style='font-size:13px;color:#2C2F34;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:.5in;margin-left:15.0pt;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:justify;line-height:24.0pt;background:white;'><span style='font-size:13px;color:#2C2F34;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:0in;margin-left:0in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:11.25pt;text-align:center;line-height:normal;background:white;'><strong><span style='font-size:16px;color:#2C2F34;' class="highlight">الأطعمه التي تحبها الكلاب</span></strong></p>
            <div style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:right;line-height:107%;font-size:15px;font-family:"Cairo",sans-serif;border:none;border-right:solid #1B4A68 3.0pt;padding:0in 8.0pt 0in 0in;'>
                <h3 dir="LTR" style='margin-top:22.5pt;margin-right:0in;margin-bottom:6.0pt;margin-left:0in;text-align:right;line-height:107%;font-size:16px;font-family:"Cambria",serif;color:#243F60;font-weight:normal;border:none;padding:0in;'><span dir="RTL" style='font-size:13px;line-height:107%;color:black;'>الأطعمة الطبيعية</span></h3>
            </div>
            <ul style="list-style-type: disc;margin-left:5px;">
                <li><strong><span style=';border:none windowtext 1.0pt;'>الجزر</span></strong><strong><span dir="LTR" style=';font-size:10.0pt;color:#2C2F34;border:none windowtext 1.0pt;'>:</span></strong><span dir="LTR" style='color:#2C2F34;'>&nbsp;</span><span style='font-size:10.0pt;color:#2C2F34;'>الجزر غذاء صحي للكلاب، ويمكن أن يساعد مضغ الجزر في إزالة البلاك من أسنانهم وتعزيز صحة الأسنان، كما أنه مصدرًا جيدًا لفيتامين أ ومفيد لجهاز مناعة الكلب لكن يجب تناوله بإعتدال حتى لا يسبب الإفراط في تناوله إلى التسمم</span><span dir="LTR" style=''>.</span></li>
                <li><strong><span style=';border:none windowtext 1.0pt;'>التفاح</span></strong><strong><span dir="LTR" style=';font-size:10.0pt;color:#2C2F34;border:none windowtext 1.0pt;'>:</span></strong><span dir="LTR" style='color:#2C2F34;'>&nbsp;</span><span style='font-size:10.0pt;color:#2C2F34;'>يوفر التفاح العديد من الفيتامينات المهمة للكلاب،</span></li>
                <li><strong><span style=';border:none windowtext 1.0pt;'>الأرز الأبيض</span></strong><strong><span dir="LTR" style=';font-size:10.0pt;color:#2C2F34;border:none windowtext 1.0pt;'>:&nbsp;</span></strong><span style='color:#2C2F34;'>يمكن أن يكون الأرز الأبيض العادي المطبوخ خيارًا جيدًا للكلب المصاب باضطراب في المعدة حيث يسهل هضمه</span><span dir="LTR" style='color:#2C2F34;'>.</span></li>
                <li><strong><span style=';border:none windowtext 1.0pt;'>منتجات الألبان</span></strong><strong><span dir="LTR" style=';font-size:10.0pt;color:#2C2F34;border:none windowtext 1.0pt;'>:&nbsp;</span></strong><span style='color:#2C2F34;'>تعتبر منتجات الألبان مثل الحليب والجبن والزبادي العادي آمنة للكلاب لكن بكميات صغيرة جدًا لأن تناولها بكثرة يؤدي إلى مشاكل كبيرة</span><span dir="LTR" style=''>.</span></li>
                <li><strong><span style=';border:none windowtext 1.0pt;'>السمك</span></strong><strong><span dir="LTR" style=';font-size:10.0pt;color:#2C2F34;border:none windowtext 1.0pt;'>:</span></strong><span dir="LTR" style='color:#2C2F34;'>&nbsp;</span><span style='font-size:10.0pt;color:#2C2F34;'>يعتبر&nbsp;</span><a href="https://www.almrsal.com/post/1010613" title="سمك السلمون"><span style='font-size:10.0pt;color:#2080C7;border:none windowtext 1.0pt;'>السلمون</span></a><span dir="LTR" style=''>&nbsp;</span><span style='font-size:10.0pt;color:#2C2F34;'>والجمبري والتونة كلها آمنة للكلاب ومصادر جيدة للبروتين، بشرط طهيها جيداً قبل تقديمها لهم</span><span dir="LTR" style='font-size:10.0pt;color:#2C2F34;'>.</span></li>
                <li><strong><span style=';border:none windowtext 1.0pt;'>الدجاج</span></strong><strong><span dir="LTR" style=';font-size:10.0pt;color:#2C2F34;border:none windowtext 1.0pt;'>:&nbsp;</span></strong><span dir="LTR"><a href="https://www.almrsal.com/post/589739" title="الدجاج في المنام"><span dir="RTL" style='font-size:10.0pt;color:#2080C7;border:none windowtext 1.0pt;'>الدجاج</span></a></span><span dir="LTR" style=''>&nbsp;</span><span style='font-size:10.0pt;color:#2C2F34;'>العادي المسلوق بدون توابل هو خيار جيد عندما يعاني الكلب من اضطراب في المعدة</span><span dir="LTR" style=''>.</span></li>
                <li><strong><span style=';border:none windowtext 1.0pt;'>زبدة الفول السوداني</span></strong><strong><span dir="LTR" style="border:none windowtext 1.0pt;">:&nbsp;</span></strong><span style='color:#2C2F34;'>زبدة الفول السوداني غير المملحة مع عدم إضافة السكر أو المحليات آمنة للكلاب لكن باعتدال</span><span dir="LTR" style='color:#2C2F34;'>.</span></li>
                <li><strong><span style=';border:none windowtext 1.0pt;'>الفشار العادي</span></strong><strong><span dir="LTR" style=';font-size:10.0pt;color:#2C2F34;border:none windowtext 1.0pt;'>:&nbsp;</span></strong><span style='color:#2C2F34;'>يمكن أن يكون الفشار العادي وجبة لذيذة للكلاب لكن بدون ملح أو زبدة أو سكر حيث يحتوي الفشار على معادن مثل&nbsp;</span><a href="https://www.almrsal.com/post/956534" title="جرعة المغنيسيوم"><span style="border:none windowtext 1.0pt;">المغنيسيوم</span></a><span dir="LTR" style='color:#2C2F34;'>&nbsp;</span><span style='color:#2C2F34;'>والفوسفور والزنك وكلها مهمة للحفاظ على صحة الكلاب</span><span dir="LTR" style=''>.</span></li>
            </ul>
            <p dir="RTL" style='margin-right:.5in;margin-left:15.0pt;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:justify;line-height:24.0pt;background:white;'><span dir="LTR" style='font-size:13px;color:#2C2F34;'>&nbsp;</span></p>
            <p dir="RTL" style='margin-right:.5in;margin-left:15.0pt;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:center;line-height:24.0pt;background:white;'><strong><span style='font-size:16px;font-family:"Arial",sans-serif;color:black;' class="highlight">نصائح خاصة بتغذية الكلاب</span></strong></p>
            <ul style="margin-bottom:0in;margin-top:0in;" type="disc">
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>اشترِ طعامًا للكلاب يكون متوفرًا تجاريًا بدلاً من صنعه في المنزل لأنه من الصعب توفير كل ما يحتاجه كلبك في نظام غذائي محلي الصنع</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>ابحث عن طعام مكتوب عليه &ldquo;كامل&rdquo; مما يعني أنه يحتوي على جميع العناصر الغذائية الموصى بها التي سيحتاجها كلبك</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>تأكد من أن الطعام مصمم لمرحلة حياة كلبك &ndash; على سبيل المثال طعام جرو يختلف عن طعام كلب بالغ أو طعام كلاب كبيرة السن</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>يبدو أن بعض الكلاب تفضل (أو لا تحب) بعض نكهات الطعام لذلك تعرف على النكهات التي تحبها</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>الكلاب من الحيوانات آكلة اللحوم مما يعني أنها يمكن أن تأكل اللحوم والأطعمة النباتية</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>يعتمد نوع وكمية الطعام الذي يحتاجه الكلب على سلالته ونوعه وعمره وصحته ونمط حياته، على سبيل المثال يحتاج كلب الراعي العامل إلى طاقة أكثر بكثير من الكلب الصغير الذي يقضي معظم اليوم في الداخل</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>إذا لم تكن متأكدًا من الكمية المناسبة لإطعام كلبك فتحدث إلى الطبيب البيطري في تصميم خطة تغذية لكلبك</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>إذا غير كلبك عاداته الغذائية أو بدأ في اكتساب الوزن أو فقده فاتصل بالطبيب البيطري للحصول على المشورة حيث قد تكون علامة على أن كلبك ليس على ما يرام</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>يقوم معظم الملاك بإطعام كلابهم مرتين في اليوم، ويمكن أن تستفيد الكلاب الصغيرة ذات أنماط الحياة النشطة من إطعامها مرتين يوميًا من أجل الحفاظ على مستويات الطاقة مرتفعة وتنظيم مستويات الجلوكوز</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>قد تستفيد الكلاب التي تواجه صعوبة في امتصاص العناصر الغذائية أو صعوبة في الحفاظ على الوزن من إطعامها عدة وجبات صغيرة يوميًا</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>إذا كنت بحاجة إلى تغيير النظام الغذائي لكلبك لأي سبب فتذكر أن تفعل ذلك ببطء وحذر حيث يمكن أن تسبب التغييرات المفاجئة في الطعام اضطرابات في المعدة لذلك تحتاج إلى إدخال الطعام الجديد تدريجيًا والتخلص التدريجي من الطعام القديم</span><span dir="LTR" style='font-size:13px;'>.</span></li>
                <li dir="RTL" style='margin-top:0in;margin-right:0in;margin-bottom:8.25pt;margin-left:15.0pt;text-align:justify;line-height:24.0pt;font-size:15px;font-family:"Cairo",sans-serif;color:#2C2F34;background:white;'><span style='font-size:13px;'>ينصح الأطباء البيطريون بعدم إطعام العظام وبقايا الطعام وقطع اللحم والفضلات الأخرى</span><span dir="LTR" style='font-size:13px;'>.</span></li>
            </ul>
            <p dir="LTR" style='margin-right:15.0pt;margin-left:.5in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:right;line-height:24.0pt;background:white;'><span style='font-size:13px;'>&nbsp;</span></p>
            <p dir="LTR" style='margin-right:15.0pt;margin-left:.5in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:right;line-height:24.0pt;background:white;'><span dir="RTL" style='font-size:13px;'>&nbsp;</span></p>
            <p dir="LTR" style='margin-right:15.0pt;margin-left:.5in;font-size:15px;font-family:"Cairo",sans-serif;margin-top:0in;margin-bottom:.0001pt;text-align:right;line-height:24.0pt;background:white;'><span dir="RTL" style='font-size:13px;'>&nbsp;</span></p>
        </div>
    </div>

@endsection